setup mobile version skeleton
mandelatuks/Portfolio pull request #1
Opened 2022-03-16 21:13 UTC by mandelatuks

**In this project for the portfolio the following was done:**

-Add HTML file
-Add CSS file
-Add images folders

2022-03-16 22:19 UTC, gemmen29 requested changes
Hi @mandelatuks, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 22:19 UTC, gemmen29 commented on index.html
> +</main>
Kindly try to match the `background image` with the Figma design and Please add the `arrow button`.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/158698953-3ea0803e-830f-4a0e-9cea-00a61f315fba.png) | ![Template 4-main-mobile - Copy - Copy](https://user-images.githubusercontent.com/24703171/158699325-341fc59e-f366-447e-be72-39d777cb869e.png) |

2022-03-16 22:19 UTC, gemmen29 commented on index.html
> +      </p>
Kindly change the `p` tag to be  `a` tag for semantic purposes.

2022-03-16 22:19 UTC, gemmen29 commented on index.html
> +  </div>
Kindly change the `div` tag to be `ul` tag and wrap each `a` tag with a `li` tag for semantic purposes.

2022-03-16 22:19 UTC, gemmen29 commented on index.html
> +</h2>
Kindly change this heading to be `h1` instead of `h2` since this is the main heading of the page.

2022-03-16 22:19 UTC, gemmen29 commented on index.html
> +</html>
Kindly change the PR description to be more descriptive like mentioning what you did exactly in this PR like:
- Add navbar. 
- Add hero section.

2022-03-17 01:16 UTC, mandelatuks commented
@gemmen29,
  I  corrected everything like in the requirement thanks for the guidance.

2022-03-17 01:24 UTC, gemmen29 approved these changes
Hi @mandelatuks, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 01:25 UTC, merged