Create contact -form-section
mandelatuks/Portfolio pull request #3
Opened 2022-03-22 23:09 UTC by mandelatuks

# the following were added:

- Add a contact form field area 
- Add submit button to the form 
- Add social icons to the form
- Add email to the form
- No linters error

2022-03-22 23:42 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @mandelatuks and @Lembani 

Good job so far! 💪
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/159594129-373b4155-2e84-4f8f-ac65-e22bb7bf05b3.gif)

## Highlights
✔️ Good README
✔️ No Linter errors
✔️ Contact form is working fine
✔️ Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 23:42 UTC, AmaduKamara commented on styles.css
> +
You are doing great so far but there are a few changes that you've left out to complete your design

[ Required Changes ]

- [ ] Please add the background image for the contact section as it's in the Figma design. It's highlighted in a green arrow in the comment photo below. Please fix that 👍 
- [ ] Kindly add the remaining social media icons that are in the Figma design.
- Spoiler Alert: You will be creating an account for all those social media icons as you go in the course program and hence, it's good you have them now in your portfolio app as you'll update their links once you create the accounts. 👍
Your Design
![image](https://user-images.githubusercontent.com/50941074/159592447-c5d0e1ca-4765-4a1d-83b0-6113dffe9bab.png)

The Figma Design
![image](https://user-images.githubusercontent.com/50941074/159592629-a2c38572-7ed2-440d-8376-7b14dc413dad.png)

2022-03-23 00:01 UTC, mandelatuks commented
@AmaduKamara 
the image was showing on my side but i hope now you can see it

![Screenshot 2022-03-23 015540](https://user-images.githubusercontent.com/38649067/159596132-9e789d8f-5f1a-414d-8f31-3e3403b9c159.png)

2022-03-23 00:06 UTC, keroloussamy approved these changes
Hi @mandelatuks, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 06:54 UTC, merged